-- MySQL Script generated by MySQL Workbench
-- Wed Mar  1 10:03:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DataLog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DataLog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DataLog` DEFAULT CHARACTER SET utf8 ;
USE `DataLog` ;

-- -----------------------------------------------------
-- Table `DataLog`.`tblSensors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DataLog`.`tblSensors` (
  `SensorID` INT NOT NULL AUTO_INCREMENT,
  `SensorType` VARCHAR(45) NULL,
  `SensorLocation` VARCHAR(45) NULL,
  PRIMARY KEY (`SensorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DataLog`.`tblData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DataLog`.`tblData` (
  `DataID` INT NOT NULL AUTO_INCREMENT,
  `TimeStamp` DATETIME NULL,
  `SensorID` INT NULL,
  `Temp` FLOAT NULL,
  PRIMARY KEY (`DataID`),
  INDEX `SensorID_idx` (`SensorID` ASC),
  CONSTRAINT `SensorID`
    FOREIGN KEY (`SensorID`)
    REFERENCES `DataLog`.`tblSensors` (`SensorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
